### ISSUE TITLE
Outclick triggers on mouseup

### ISSUE THREAD

**Issue by JulianZschieschang** [babakfp/svelte-outclick#4] opened 2021-11-19 11:20 UTC
When the mouse button is pressed in the Excluded component and leaves the area, the outclick event is triggered.
This is problematic for input fields or other input options that use the mouse. 
Maybe you could include the possibility to decide if the event triggers on `click` or only on `mousedown`.

In the video clip you can see this problem.
Minimal example: [REPL](https://svelte.dev/repl/b6e91dda9b4c44fd98a7d2d2c8d729c1)

https://user-images.githubusercontent.com/68694053/142614085-e9507ccc-6252-44a2-9816-1ed634c6f84b.mp4

**Comment by babakfp** [comment] 2021-11-29 01:50
God damn it. I check Github almost every day but Github never noticed me about this post.
I did know about this behavior but I didn't know that it can cause such a problem as you showed in the video.
I will fix it soon.
Thank you🌼

**Comment by babakfp** [comment] 2021-11-29 02:43
Nice👌😶

![Annotation 2021-11-29 060803](https://user-images.githubusercontent.com/44144724/143800143-c91b3e50-a83b-4630-8ba0-5574593b520a.png)

ERROR:
```
<svelte:window> tags cannot be inside elements or blocks
```

I can't even talk with the discord community or create an issue on the Svelte repo because I'm banned😂

**Comment by babakfp** [comment] 2021-11-29 03:09
What is the downside of using `on:mousedown` instead of `on:click`?
I don't want to add an extra option for `mousedown` because its functionality is what we actually need.
🤔🤷‍♂️

**Comment by t-heuser** [comment] 2021-11-29 06:43
@babakfp Don't think there is a downside to this. Just keep in mind to also add on:keydown to respect A11Y. Have a look at https://www.w3.org/TR/WCAG20-TECHS/SCR20.html, there it says to use mousedown with keydown combined and everything should be fine.

**Comment by babakfp** [comment] 2021-11-29 15:09
Thanks @oneserv-heuser 
Using key down doesn't make sense, at least in this example.

**Comment by t-heuser** [comment] 2021-11-30 09:04
@babakfp Why doesn't it make sense? It makes a lot of sense as now this module doesn't respect A11Y anymore. Let me show you an example: https://svelte.dev/repl/b50a0d538dd549f9aa55cb0ccdbd0f6c

With the old version of this module it was possible to open the box and then use the keyboard to navigate to the buttons. The box was closed as soon as you interacted with any other element outside the box with the keyboard. With the new version you published this doesn't work anymore.

The following fixes this:
```svelte
<svelte:window on:mousedown={handleClick} on:keydown={handleClick}/>
```

The addition of `on:keydown` as supposed by https://www.w3.org/TR/WCAG20-TECHS/SCR20.html fixes it and respects A11Y.

**Comment by babakfp** [comment] 2021-11-30 14:48
I did some tests and what we are going to achieve with `on:mousedown` and `on:keydown` isn't the same as `on:click`.
If we use `on:click`, only space key press will close the box in your demo, but by using `on:mousedown` and `on:keydown`, any key press will close the box (obviously). Maybe there are other things happens behind the scenes that we don't know about. So, is there a solution that we can use 'on:clikc' and prevent its issue?

---

Add the package version number in your REPL's like this:
Because after the new release, they are not useable...
```
import OutClick from 'svelte-outclick@2.4.3'
import OutClick from 'svelte-outclick@<version>'
```

**Comment by t-heuser** [comment] 2021-11-30 15:12
@babakfp I'm shortening this process and just created a PR #5.
This fixes the described issue and now provides the same functionality before your fix for the keyboard event.
I'm listening for the keyboard press event and then call the handleClick function if the pressed key is "Enter".
So your described issue is also fixed with my PR and everyone should be happy 😄

**Comment by babakfp** [comment] 2021-11-30 20:59
Check out these demos. In both of the demos, click on the "Open" button, then press the "Space" key. You will see that different thing happen.

After clicking on the "Open" button and after that I click on the "Space" key...

https://user-images.githubusercontent.com/44144724/144126960-1422b161-e908-43b5-90f4-b6c6ebf300c4.mp4

### Demo
- [svelte-outclick #4 - on:mousedown, on:keydown](https://svelte.dev/repl/bb9cfc4fe9264daf886fa8bec9da245e?version=3.44.2)
- [svelte-outclick #4 - on:click](https://svelte.dev/repl/57ddb548957c43ff9249f82d1ddb96d1?version=3.44.2)

I'm using the latest version of Chrome browser.

**Comment by t-heuser** [comment] 2021-12-01 09:09
@babakfp Here is a REPL with my solution as provided in #5 : [svelte-outclick #4 - with fixed issue in PR #5](https://svelte.dev/repl/3c3b354e44ff4d869f51c377cfb1dfaf?version=3.44.2)

Now it just looks if the Enter key was pressed and ignores other keys.

**Comment by babakfp** [comment] 2021-12-01 14:48
Hi @oneserv-heuser.
Thank you for your PR.
Please check [this comment](https://github.com/babakfp/svelte-outclick/issues/4#issuecomment-983015606). The problem here is different.
Open this demo [svelte-outclick #4 - on:click](https://svelte.dev/repl/57ddb548957c43ff9249f82d1ddb96d1?version=3.44.2), click on "Open" button and then press ** Enter** key. You will see that nothing happens. But in the [svelte-outclick #4 - on:mousedown, on:keydown](https://svelte.dev/repl/bb9cfc4fe9264daf886fa8bec9da245e?version=3.44.2) demo, the box gets closed.
Thanks again😘

**Comment by t-heuser** [comment] 2021-12-02 10:03
@babakfp 
> But in the [svelte-outclick #4 - on:mousedown, on:keydown](https://svelte.dev/repl/bb9cfc4fe9264daf886fa8bec9da245e?version=3.44.2) demo, the box gets closed.

I think youre mixing two things. When hovering with the mouse (without clicking anything) over any object and then pressing a key on the keyboard the target of the keyboard event is always `body` as nothing is selected (focused) with the keyboard. To change the target of the keyboard event you have to click on an element or use the tab key to navigate through the page. 

So yes, the behaviour is different, but it works as intended. [In my version](https://svelte.dev/repl/3c3b354e44ff4d869f51c377cfb1dfaf?version=3.44.2), which represent the PR, only the enter key will fire the `handeClick` function. So i don't think that there is any issue in my solution as everything works as intended, you just have to separate the keyboard and the mouse in your consideration.

**Closed as completed** 2021-12-09 19:51 UTC

**Comment by babakfp** [comment] 2021-12-09 20:06
@JulianZschieschang 
@oneserv-heuser 
Add 2 new props (`useMousedown`(bool), `useKeydown`(bool)) to your component to get the desired result.

**Comment by babakfp** [comment] 2022-01-05 08:25
Hi
I decided to check out this issue again and I find a way, I fixed [the difference between `on:click` and `on:mousedown`](https://github.com/babakfp/svelte-outclick/issues/4#issuecomment-983015606) by ignoring the `document.body` for `on:keydown` from triggering the `outclick` event. Thank you @oneserv-heuser, @JulianZschieschang, @MarianNapi for your contribution❤️

Please check out the new [**version 3.0.0**](https://github.com/babakfp/svelte-outclick/blob/main/CHANGELOG.md)
